version: '3.8'

services:
  # 1. The Database (Backend)
  db:
    image: postgres:15-alpine
    container_name: classroom_db_secure
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dockerpass
      POSTGRES_DB: classroom_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: classroom_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Access at localhost:5050
    depends_on:
      - db

volumes:
  postgres_data: